class CompensationDatabaseModel:
    """
    create if id doesn't exist
    update if it does. meaning don't set compensations 
    that have been set to 1,0 to -1 while updating
    """
    def __init__(self, **kwargs):
        self.id = none
        self.video_id = kwargs.get('video_id')
        self.assessment_type = kwargs.get('assessment_type')
        self.original_video_url = kwargs.get('original_video_url', 'na')
        self.two_leg_squat_front_foot_turns_out_left_limb_curv = kwargs.get('two_leg_squat_front_foot_turns_out_left_limb_curv', -1)
        self.two_leg_squat_front_foot_turns_out_right_limb_curv = kwargs.get('two_leg_squat_front_foot_turns_out_right_limb_curv', -1)
        self.two_leg_squat_front_knee_moves_in_left_limb_curv = kwargs.get('two_leg_squat_front_knee_moves_in_left_limb_curv', -1)
        self.two_leg_squat_front_knee_moves_out_left_limb_curv = kwargs.get('two_leg_squat_front_knee_moves_out_left_limb_curv', -1)
        self.two_leg_squat_front_hip_shift_left_limb_curv = kwargs.get('two_leg_squat_front_hip_shift_left_limb_curv', -1)
        self.two_leg_squat_front_hip_shift_right_limb_curv = kwargs.get('two_leg_squat_front_hip_shift_right_limb_curv', -1)
        self.two_leg_squat_front_heel_foot_rise_right_limb_curv = kwargs.get('two_leg_squat_front_heel_foot_rise_right_limb_curv', -1)
        self.two_leg_squat_side_forward_lean_curv = kwargs.get('two_leg_squat_side_forward_lean_curv', -1)
        self.two_leg_squat_side_arms_fall_forward_curv = kwargs.get('two_leg_squat_side_arms_fall_forward_curv', -1)
        self.one_leg_squat_right_knee_moves_in_right_limb_curv = kwargs.get('one_leg_squat_right_knee_moves_in_right_limb_curv', -1)
        self.one_leg_squat_right_knee_moves_in_left_limb_curv = kwargs.get('one_leg_squat_right_knee_moves_in_left_limb_curv', -1)
        self.one_leg_squat_right_uncontrolled_trunk_right_fusionetics = kwargs.get('one_leg_squat_right_uncontrolled_trunk_right_fusionetics', -1)
        self.one_leg_squat_right_uncontrolled_trunk_left_curv = kwargs.get('one_leg_squat_right_uncontrolled_trunk_left_curv', -1)
        self.one_leg_squat_right_loss_of_balance_fusionetics = kwargs.get('one_leg_squat_right_loss_of_balance_fusionetics', -1)
        self.one_leg_squat_left_loss_of_balance_curv = kwargs.get('one_leg_squat_left_loss_of_balance_curv', -1)
        self.one_leg_squat_left_knee_moves_in_left_limb_curv = kwargs.get('one_leg_squat_left_knee_moves_in_left_limb_curv', -1)
        self.one_leg_squat_left_knee_moves_in_right_limb_fusionetics = kwargs.get('one_leg_squat_left_knee_moves_in_right_limb_fusionetics', -1)
        self.one_leg_squat_left_uncontrolled_trunk_left_curv = kwargs.get('one_leg_squat_left_uncontrolled_trunk_left_curv', -1)
        self.one_leg_squat_left_knee_moves_in_left_limb_fusionetics = kwargs.get('one_leg_squat_left_knee_moves_in_left_limb_fusionetics', -1)
        self.one_leg_squat_left_knee_moves_in_left_limb_threshold = kwargs.get('one_leg_squat_left_knee_moves_in_left_limb_threshold', -1)
        self.one_leg_squat_left_knee_moves_in_right_limb_curv = kwargs.get('one_leg_squat_left_knee_moves_in_right_limb_curv', -1)
        self.one_leg_squat_left_knee_moves_in_right_limb_threshold = kwargs.get('one_leg_squat_left_knee_moves_in_right_limb_threshold', -1)
        self.one_leg_squat_right_knee_moves_in_left_limb_fusionetics = kwargs.get('one_leg_squat_right_knee_moves_in_left_limb_fusionetics', -1)
        self.one_leg_squat_right_knee_moves_in_left_limb_threshold = kwargs.get('one_leg_squat_right_knee_moves_in_left_limb_threshold', -1)
        self.one_leg_squat_right_knee_moves_in_right_limb_fusionetics = kwargs.get('one_leg_squat_right_knee_moves_in_right_limb_fusionetics', -1)
        self.one_leg_squat_right_knee_moves_in_right_limb_threshold = kwargs.get('one_leg_squat_right_knee_moves_in_right_limb_threshold', -1)
        self.one_leg_squat_left_uncontrolled_trunk_left_fusionetics = kwargs.get('one_leg_squat_left_uncontrolled_trunk_left_fusionetics', -1)
        self.one_leg_squat_left_loss_of_balance_fusionetics = kwargs.get('one_leg_squat_left_loss_of_balance_fusionetics', -1)
        self.one_leg_squat_right_loss_of_balance_curv = kwargs.get('one_leg_squat_right_loss_of_balance_curv', -1)
        self.one_leg_squat_right_uncontrolled_trunk_left_fusionetics = kwargs.get('one_leg_squat_right_uncontrolled_trunk_left_fusionetics', -1)
        self.one_leg_squat_right_uncontrolled_trunk_right_curv = kwargs.get('one_leg_squat_right_uncontrolled_trunk_right_curv', -1)
        self.two_leg_squat_front_foot_turns_out_left_limb_fusionetics = kwargs.get('two_leg_squat_front_foot_turns_out_left_limb_fusionetics', -1)
        self.two_leg_squat_front_foot_turns_out_right_limb_fusionetics = kwargs.get('two_leg_squat_front_foot_turns_out_right_limb_fusionetics', -1)
        self.two_leg_squat_front_foot_turns_out_right_limb_threshold = kwargs.get('two_leg_squat_front_foot_turns_out_right_limb_threshold', -1)
        self.two_leg_squat_front_foot_turns_out_left_limb_threshold = kwargs.get('two_leg_squat_front_foot_turns_out_left_limb_threshold', -1)
        self.two_leg_squat_side_forward_lean_fusionetics = kwargs.get('two_leg_squat_side_forward_lean_fusionetics', -1)
        self.two_leg_squat_side_arms_fall_forward_fusionetics = kwargs.get('two_leg_squat_side_arms_fall_forward_fusionetics', -1)
        self.two_leg_squat_side_arms_fall_forward_threshold = kwargs.get('two_leg_squat_side_arms_fall_forward_threshold', -1)
        self.two_leg_squat_side_forward_lean_threshold = kwargs.get('two_leg_squat_side_forward_lean_threshold', -1)
        self.two_leg_squat_front_knee_moves_out_right_limb_curv = kwargs.get('two_leg_squat_front_knee_moves_out_right_limb_curv', -1)
        self.two_leg_squat_front_knee_moves_out_right_limb_fusionetics = kwargs.get('two_leg_squat_front_knee_moves_out_right_limb_fusionetics', -1)
        self.two_leg_squat_front_knee_moves_out_right_limb_threshold = kwargs.get('two_leg_squat_front_knee_moves_out_right_limb_threshold', -1)
        self.two_leg_squat_front_knee_moves_out_left_limb_fusionetics = kwargs.get('two_leg_squat_front_knee_moves_out_left_limb_fusionetics', -1)
        self.two_leg_squat_front_knee_moves_out_left_limb_threshold = kwargs.get('two_leg_squat_front_knee_moves_out_left_limb_threshold', -1)
        self.two_leg_squat_front_knee_moves_in_right_limb_curv = kwargs.get('two_leg_squat_front_knee_moves_in_right_limb_curv', -1)
        self.two_leg_squat_front_knee_moves_in_right_limb_fusionetics = kwargs.get('two_leg_squat_front_knee_moves_in_right_limb_fusionetics', -1)
        self.two_leg_squat_front_knee_moves_in_right_limb_threshold = kwargs.get('two_leg_squat_front_knee_moves_in_right_limb_threshold', -1)
        self.two_leg_squat_front_knee_moves_in_left_limb_fusionetics = kwargs.get('two_leg_squat_front_knee_moves_in_left_limb_fusionetics', -1)
        self.two_leg_squat_front_knee_moves_in_left_limb_threshold = kwargs.get('two_leg_squat_front_knee_moves_in_left_limb_threshold', -1)
        self.two_leg_squat_front_hip_shift_right_limb_fusionetics = kwargs.get('two_leg_squat_front_hip_shift_right_limb_fusionetics', -1)
        self.two_leg_squat_front_hip_shift_right_limb_threshold = kwargs.get('two_leg_squat_front_hip_shift_right_limb_threshold', -1)
        self.two_leg_squat_front_hip_shift_left_limb_fusionetics = kwargs.get('two_leg_squat_front_hip_shift_left_limb_fusionetics', -1)
        self.two_leg_squat_front_hip_shift_left_limb_threshold = kwargs.get('two_leg_squat_front_hip_shift_left_limb_threshold', -1)
        self.two_leg_squat_front_heel_foot_rise_right_limb_fusionetics = kwargs.get('two_leg_squat_front_heel_foot_rise_right_limb_fusionetics', -1)
        self.two_leg_squat_front_heel_foot_rise_right_limb_threshold = kwargs.get('two_leg_squat_front_heel_foot_rise_right_limb_threshold', -1)